### ISSUE TITLE
IFile doesn't define ReadLines

### ISSUE THREAD

**Issue by sandeepiiit** [jozefizso/SystemWrapper#10]
IFile doesn't have a definition of File.ReadLines() method. This is more efficient than File.ReadAllLines() for larger files and would be a good addition IMHO.

https://msdn.microsoft.com/en-us/library/dd383503(v=vs.110).aspx
public static IEnumerable<string> ReadLines(
	string path
)

**Comment by jozefizso** [comment]
Pull request would be welcome.

**Comment by jozefizso** [comment]
Implemented in v0.11.0
