### ISSUE TITLE
Missing Methods on IEnvironment

### ISSUE THREAD

**Issue by wiltaylor** [jozefizso/SystemWrapper#14]
Main ones of note are ExpandEnvironmentVariables and GetFolderPath but the other ones are missing too.

**Comment by Doommaker** [comment]
This is rather kind of a bug rather then enhancement. Anything missing prevents the user from using a wrapper because he would need to have some parts implemented with SystemWrapper and other with something else, which is really very odd.

**Comment by jozefizso** [comment]
Methods `ExpandEnvironmentVariables()` and `GetFolderPath()` added in release v0.15

**Comment by jozefizso** [comment]
Bug would imply there is problematic behavior in the wrapper implementation.

This is an **enhancement** + **help wanted** as it requires extending existing interface in SystemWrapper.

Anybody missing functionality in the SystemWrapper is free to implement it and create pull request.

**Comment by cjbush** [comment]
I have a pull request open for this: https://github.com/jozefizso/SystemWrapper/pull/24

**Comment by jozefizso** [comment]
Please reopen if you miss other methods.
