### ISSUE TITLE
StreamWriterWrap doesn't invoke Dispose on StreamWriterInstance

### ISSUE THREAD

**Issue by Doommaker** [jozefizso/SystemWrapper#16]
StreamWriterWrap doesn't invoke Dispose on StreamWriterInstance. When using this like in the example Flush method of StreamWriterInstance is not invoke during Dispose because Dispose is invoked on base class of wrap (which is TextWriter) and Dispose on StreamWriterInstance is not invoked.

`using (var writer = new StreamWriterWrap("filename, false))
{
   writer.Write("content");
}`

So when using it as above the "content" will not be written into the file.

**Comment by jozefizso** [comment]
Should be fixed by commit ba9f65ad0e89b32de796400deebbef160cd07671 and released in v0.14
