### ISSUE TITLE
SqlClient related factories not added to project

### ISSUE THREAD

**Issue by cieplok** [jozefizso/SystemWrapper#33]
Following classes: 
- SqlCommandFactory
- SqlConnectionFactory
- SqlDataAdapterFactory
- SqlDataAdapterWrap 
- SqlParameterCollectionWrap

Are implemented and added to source code but they are not added to SystemWrapper.csproj and thus they are no compiled.
Is this intentional or are they removed/not added by accident?

**Comment by jozefizso** [comment]
These factories and wrapper were not added to the `SystemWrapper.csproj` in the original pull request and I did not notice they are missing.

There may be more missing classes in the project.

**Comment by jozefizso** [comment]
This should be fixed in v0.20.0
