### ISSUE TITLE
IDateTime doesn't implement IComparable

### ISSUE THREAD

**Issue by galmok** [jozefizso/SystemWrapper#48]
I was using linq with DateTime objects, now converted to IDateTime, but ordering them didn't work due to IComparable not being implemented for IDateTime.

The original DateTime object inherits from these interfaces:

IComparable, IFormattable, IConvertible, ISerializable, IComparable<DateTime>,IEquatable<DateTime>

Is this something IDateTime is supposed to offer?

**Comment by jozefizso** [comment]
Yes, it makes sense for the wrapper to implement all the interfaces of the wrapped type.

**Comment by rbarillec** [comment]
See [here](https://github.com/jozefizso/SystemWrapper/pull/56) for a change which adds support for equality and comparison.
