### ISSUE TITLE
Unity thinks the SystemWrapper.dll is broken

### ISSUE THREAD

**Issue by m-ender** [jozefizso/SystemWrapper#50]
Do you (or someone else) have any experience with using SystemWrapper in a Unity project? When I add the SystemWrapper.dll and the SystemInterface.dll to the project, Unity complains that the former is broken:

> Unloading broken assembly Assets/Plugins/SystemWrapper/SystemWrapper.dll, this assembly can cause crashes in the runtime.

Weirdly enough, I seem to be able to use it anyway. Unfortunately, I don't get any other error message to indicate what might be causing this.

**Comment by jozefizso** [comment]
I don't know why Unity has this issue with SystemWrapper libraries.

**Comment by adrianoc-unity3d** [comment]
The problem looks to be that Mono does not provide some libraries/types that are Windows specific. For instance `System.DirectoryServices.AccountManagement.dll`. 

I'm experimenting filtering (#if) these types in https://github.com/adrianoc-unity3d/SystemWrapper/tree/targetmono. 

With these changes Unity does not complain anymore. I am not sure if I was too aggressive and excluded way too many types (maybe removing any types that references `System.DirectoryServices.AccountManagement.dll` would be enough)

**Comment by jozefizso** [comment]
As Unity does not provide all of the reference assemblies, SystemWrapper will not work correctly in it.

Pull request to add support for Unity is welcome.
