### ISSUE TITLE
No wrapper for System.Configuration.Configuration

### ISSUE THREAD

**Issue by chrischu** [jozefizso/SystemWrapper#6]
Unfortunately there is no wrapper for System.Configuration.Configuration (the return type of the Open*Configuration-methods in IConfigurationManager).

A wrapper like that would be very useful though!

**Comment by jozefizso** [comment]
Released in v0.10.1

**Comment by chrischu** [comment]
When is the new NuGet package going to get released?

**Comment by jozefizso** [comment]
Sorry, I only tagged the release and did not increment the version number. It's building now and should be available on NuGet.org in minutes.

**Comment by chrischu** [comment]
Cool, thanks for the quick response!
